IT210B-4/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using IT210B_4.Data;
using IT210B_4.Data.Dao;
using IT210B_4.Models;
using System.Security.Claims;

namespace IT210B_4.Controllers
{
    [Authorize]
    public class ItemsController : Controller
    {
        private readonly IItemDao _dao;

        public ItemsController(IAtlasSettings settings)
        {
            _dao = new ItemDao(settings);
        }

        // GET: Items
        public async Task<IActionResult> Index()
        {
            var UserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            IEnumerable<Item> items = await _dao.Read(UserId);
            ViewData["list"] = items;
            ViewData["userId"] = UserId;
            return View();
        }

        // POST: Items/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserId,Text,Date")] Item item)
        {
            if (ModelState.IsValid)
            {
                await _dao.Create(item);
                return RedirectToAction(nameof(Index));
            }
            return View(item);
        }

        // POST: Items/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,UserId,Text,Done,Date")] Item item)
        {
            if (id != item.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    item.Done = !item.Done;
                    await _dao.Update(item);
                }
                catch (DbUpdateConcurrencyException)
                {
                    return NotFound();
                }
            }
            return RedirectToAction(nameof(Index));
        }

        // POST: Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            await _dao.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

IT210B-4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IT210B_4</title>
    <link rel="stylesheet" href="~/css/materialize.css" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav>
            <div class="nav-wrapper">
                <a class="brand-logo" asp-area="" asp-controller="Items" asp-action="Index">IT210B_4</a>
                <ul class="right hide-on-med-and-down" id="nav-mobile">
                    <li>
                        <a class="waves-effect waves-light btn" asp-area="" asp-controller="Items" asp-action="Index">Home</a>
                    </li>
                    <partial name="_LoginPartial" />
                    <li>
                        <a class="waves-effect waves-light btn" asp-area="" asp-controller="Items" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - IT210B_4 - <a asp-area="" asp-controller="Items" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/materialize.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>